Fix github workflow and update dependencies
- Previous workflow was running pre-commit under the runner's default
Python (Python 3.14 at the time) which is not compatible with Black yet
and causes error:
"error: cannot format ...: module 'ast' has no attribute 'Str'".
Fixed by pinning to Python 3.12

- Let Black auto-reformat recent Python scripts.

- Added `pre-commit` as a dev dependency to `pyproject.toml`.

- Remove default env name in `env_base.yml` (make it easier to create
different test envs with different names without having to modify the
yaml file).

- Relax `astra-toolbox` min version to 2.3 to let `aarch64` users get
compartible version from `conda-forge`. Note: `aarch64` still hasn't
been properly tested yet.

TODOs:

- Edit README.md: do `pip install -e ".[dev]"` to get the dev
dependencies including `pre-commit`

- Replace `env.yml` with `env_base.yml` completely once devs are
comfortable to switch.

- Edit instruction to manually add an environment name, e.g.
`conda env create -f env_base.yml -n lion_dev`

- Add note to `README.md`: Can ignore error:
```
ensureconda 1.6.0 requires conda-package-streaming, which is not
installed.
```